#!/bin/bash
# HTML injection for server-less applications
# brian@theconnman.com
# Version 1.1.1

prog="./injector"

usage() {
	echo "Usage: $prog [-r root] [-d dist] [-kwv]"
	echo "       $prog -h for help."
	exit
}

showhelp() {
	echo "Usage: $prog: [-r root] [-d dist] [-kwv]"
	echo "Injector: HTML injection for server-less applications"
	echo "  -r: root HTML directory to be crawled recursively"
	echo "  -d: distribution directory"
	echo "  -k: keep injected files"
	echo "  -w: watch root directory for changes"
	echo "  -v: verbose output"
	echo "  -h: this help message"
}

refresh() {
	echo -e "\nRefreshing"

	# Remove old files
	for f in $(find $root -name "*"); do
		if [ -f $f ]; then
			rm -f $dist${f#$root};
		fi
	done
	
	# Resolve all files in the source directory
	for f in $(find $root -name "*"); do
		if [ -f $f ]; then
			resolvefile $f;
		fi
	done
}

layouts() {
	for f in $(find $root -type f -print | xargs grep -h "<% injector" | sed -n 's/.*src="\(.*\)".*/\1/p'); do
		rm -f $dist/$f
	done
	find $dist -type d -empty -exec rmdir {} \;
}

# Initialize variables and define defaults
root=.
dist=dist/
keep=false
watch=false
verbose=false

# Get arguments

while getopts "kwvr:d:h" name; do
	case $name in
		r)  root=$OPTARG;;
		d)  dist=$OPTARG;;
		h)  showhelp $0;;
		k)  keep=true;;
		w)  watch=true;;
		v)  verbose=true;;
		[?])  usage $0;;
	esac
done

# Resolves injections within a single file
resolvefile() {
	local loc=$dist/${1#$root}
	
	# Check to see if file has already been resolved
	if [[ ! -f $loc ]]; then
	
		# Create folder and blank file
		mkdir -p $(dirname $loc)
		touch $loc
		if [[ $verbose == true ]]; then
			echo "Resolving ${1#$root}"
		fi
		
		while read line || [[ -n "$line" ]]; do
			if [[ $line == *"<% injector"* ]]; then
			
				# Find injected file location
				local depen=`expr "$line" : '^.*src="\(.*\)".*'`
				
				# Resolve injected file if it hasn't been already
				if [ ! -f $dist/$depen ]; then
					resolvefile $root$depen
				fi
				cat $dist/$depen >> $loc;
			else
				echo $line >> $loc;
			fi
		done < $1
	fi
}

# Make distribution directory
mkdir -p $dist/

if [[ $watch == true ]]; then
	chsum1=""
	
	while [[ true ]]
    do
        chsum2=`find $root -type f -exec md5sum {} \;`
        if [[ $chsum1 != $chsum2 ]] ; then           
            refresh
            chsum1=$chsum2
        fi
        sleep 2
    done
else
	refresh
fi

if [[ $keep == false ]]; then
	layouts
fi